name: build

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: ci_env
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   name: build plugin
                uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
                with:
                    arguments: buildPlugin
            -   name: publish plugin
                uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
                with:
                    arguments: publishPlugin
                env:
                    ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.ORG_GRADLE_PROJECT_INTELLIJPUBLISHTOKEN }}

